title: Japan Chapter
description: >-
  Regional site for the Japan Chapter of the AI Alliance 
baseurl: "/japan"
url: "https://the-ai-alliance.github.io"

google_tag_id:  G-RNHLN944B5
discord_link: https://discord.gg/2MMCVs76Sr
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from


